*----------------------------------------------------------------------*
***INCLUDE LZKIG_CN_0004F01.
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form transfer_to_extensionin
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM TRANSFER_TO_EXTENSIONIN USING IS_BAPI_EXTENSIONIN TYPE ANY
                             CHANGING CS_BAPIPAREX TYPE BAPIPAREX.

  DATA LV_DISTANCE_CHARACTERS TYPE I.

  FIELD-SYMBOLS <LV_ANY> TYPE ANY.

  DESCRIBE DISTANCE BETWEEN CS_BAPIPAREX-STRUCTURE AND CS_BAPIPAREX-VALUEPART1
           INTO LV_DISTANCE_CHARACTERS IN CHARACTER MODE.

  ASSIGN CS_BAPIPAREX+LV_DISTANCE_CHARACTERS(*) TO <LV_ANY>

  CASTING LIKE IS_BAPI_EXTENSIONIN.

  <LV_ANY> = IS_BAPI_EXTENSIONIN.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_return_msg
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_RETURN_MSG USING IV_MSGTY.

  DATA LS_RETURN LIKE LINE OF GT_RETURN.

  CLEAR LS_RETURN.

  LS_RETURN-TYPE = IV_MSGTY.
  LS_RETURN-ID = SY-MSGID.
  LS_RETURN-NUMBER = SY-MSGNO.
  LS_RETURN-MESSAGE_V1 = SY-MSGV1.
  LS_RETURN-MESSAGE_V2 = SY-MSGV2.
  LS_RETURN-MESSAGE_V3 = SY-MSGV3.
  LS_RETURN-MESSAGE_V4 = SY-MSGV4.

  APPEND LS_RETURN TO GT_RETURN.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_header_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_HEADER_DATA USING IS_PRHEADER TYPE ZSMM_PRHEADER
                               IS_PRHEADERX TYPE ZSMM_PRHEADERX
                      CHANGING ES_PR_BAPI_HEADER TYPE BAPIMEREQHEADER
                               ES_PR_BAPI_HEADERX TYPE BAPIMEREQHEADERX.

*>구매 요청 번호
  ES_PR_BAPI_HEADER-PREQ_NO = IS_PRHEADER-BANFN.
  ES_PR_BAPI_HEADERX-PREQ_NO = IS_PRHEADERX-BANFN.

*>오더 유형(구매)
  IF NOT IS_PRHEADER-BSART IS INITIAL.
    ES_PR_BAPI_HEADER-PR_TYPE = IS_PRHEADER-BSART.
    ES_PR_BAPI_HEADERX-PR_TYPE = IS_PRHEADERX-BSART.
  ELSE.
    MESSAGE S017(ZMM01) WITH GC_BSART_TXT.
    PERFORM SET_RETURN_MSG USING 'E'.
  ENDIF.

*> 생성지시자(구매요청/납품일정라인)
  ES_PR_BAPI_HEADER-CREATE_IND = IS_PRHEADER-ESTKZ.
  ES_PR_BAPI_HEADERX-CREATE_IND = IS_PRHEADERX-ESTKZ.

*> 자동 공급처 결정
  ES_PR_BAPI_HEADER-AUTO_SOURCE = IS_PRHEADER-KZZUO.
  ES_PR_BAPI_HEADERX-AUTO_SOURCE = IS_PRHEADER-KZZUO.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_header_text
*&---------------------------------------------------------------------*
*& text

*&---------------------------------------------------------------------*
FORM SET_HEADER_TEXT TABLES IT_PRHEADERTEXT STRUCTURE ZSMM_PRHEADERTEXT
                               ET_PR_BAPI_HEADTEXT STRUCTURE BAPIMEREQHEADTEXT.

  DATA: LS_PR_BAPI_HEADTEXT TYPE BAPIMEREQHEADTEXT.

  TYPES: BEGIN OF LTY_TEXTTABLE,
           LINE(4096),
         END OF LTY_TEXTTABLE.

  DATA: LT_TEXT_CONV_RST LIKE TABLE OF TLINE,
        LT_TEXT_CONV     TYPE TABLE OF LTY_TEXTTABLE,
        LS_TEXT_CONV     TYPE LTY_TEXTTABLE.

  CLEAR: ET_PR_BAPI_HEADTEXT.

  SORT IT_PRHEADERTEXT BY TDID.

  DATA(LT_TMP_HEADTEXT) = IT_PRHEADERTEXT[].
  SORT LT_TMP_HEADTEXT BY TDID.
  DELETE ADJACENT DUPLICATES FROM LT_TMP_HEADTEXT COMPARING TDID.

  LOOP AT LT_TMP_HEADTEXT INTO DATA(LS_TMP_HEADTEXT).
    READ TABLE IT_PRHEADERTEXT WITH KEY TDID = LS_TMP_HEADTEXT-TDID
                               BINARY SEARCH
                               TRANSPORTING NO FIELDS.
    CLEAR LT_TEXT_CONV.
    LOOP AT IT_PRHEADERTEXT INTO DATA(LS_PRHEADERTEXT) FROM SY-TABIX.
      IF LS_PRHEADERTEXT-TDID NE LS_TMP_HEADTEXT-TDID.
        EXIT.
      ENDIF.

      CLEAR LS_TEXT_CONV.
      LS_TEXT_CONV-LINE = LS_PRHEADERTEXT-TEXT_LINE.
      APPEND LS_TEXT_CONV TO LT_TEXT_CONV.
    ENDLOOP.

    IF NOT LT_TEXT_CONV[] IS INITIAL.
      CALL FUNCTION 'CONVERT_STREAM_TO_ITF_TEXT'
        EXPORTING
          LANGUAGE    = SY-LANGU
        TABLES
          TEXT_STREAM = LT_TEXT_CONV
          ITF_TEXT    = LT_TEXT_CONV_RST.
    ENDIF.

    LOOP AT LT_TEXT_CONV_RST INTO DATA(LS_TEXT_CONV_RST).
      CLEAR LS_PR_BAPI_HEADTEXT.
      LS_PR_BAPI_HEADTEXT-TEXT_ID = LS_TMP_HEADTEXT-TDID.
      LS_PR_BAPI_HEADTEXT-TEXT_FORM = LS_TEXT_CONV_RST-TDFORMAT.
      LS_PR_BAPI_HEADTEXT-TEXT_LINE = LS_TEXT_CONV_RST-TDLINE.
      APPEND LS_PR_BAPI_HEADTEXT TO ET_PR_BAPI_HEADTEXT.
    ENDLOOP.

  ENDLOOP.


ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_item_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_ITEM_DATA TABLES IT_PRITEM STRUCTURE ZSMM_PRITEM
                             ET_PR_BAPI_ITEM STRUCTURE BAPIMEREQITEMIMP.

  DATA: LS_PR_BAPI_ITEM TYPE BAPIMEREQITEMIMP,
        LV_ITEM_NO      TYPE BNFPO.

  CLEAR ET_PR_BAPI_ITEM.

  LOOP AT IT_PRITEM INTO DATA(LS_PRITEM).
    CLEAR: LS_PR_BAPI_ITEM.

*> 구매 요청 품목 번호
    IF NOT LS_PRITEM-BNFPO IS INITIAL.
      LS_PR_BAPI_ITEM-PREQ_ITEM = LS_PRITEM-BNFPO.
      LV_ITEM_NO = LS_PRITEM-BNFPO.
    ELSE.
      MESSAGE S017(ZMM01) WITH GC_BNFPO_TXT.
      PERFORM SET_RETURN_MSG USING 'E'.
      CONTINUE.
    ENDIF.

*> 구매그룹
    IF NOT LS_PRITEM-EKGRP IS INITIAL.
      LS_PR_BAPI_ITEM-PUR_GROUP = LS_PRITEM-EKGRP.
    ELSE.
      MESSAGE S016(ZMM01) WITH GC_EKGRP_TXT LV_ITEM_NO.
      PERFORM SET_RETURN_MSG USING 'E'.
    ENDIF.

*> 요청자 이름
    LS_PR_BAPI_ITEM-PREQ_NAME = LS_PRITEM-AFNAM.

*> 내역
    LS_PR_BAPI_ITEM-SHORT_TEXT = LS_PRITEM-TXZ01.

*> 자재번호
    IF NOT LS_PRITEM-MATNR IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
        EXPORTING
          INPUT        = LS_PRITEM-MATNR
        IMPORTING
          OUTPUT       = LS_PR_BAPI_ITEM-MATERIAL_LONG
        EXCEPTIONS
          LENGTH_ERROR = 1
          OTHERS       = 2.

      IF SY-SUBRC NE 0.
        PERFORM SET_RETURN_MSG USING 'E'.
      ENDIF.
    ENDIF.

*> 플랜트
    IF NOT LS_PRITEM-WERKS IS INITIAL.
      LS_PR_BAPI_ITEM-PLANT = LS_PRITEM-WERKS.
    ELSE.
      MESSAGE S016(ZMM01) WITH GC_WERKS_TXT LV_ITEM_NO.
      PERFORM SET_RETURN_MSG USING 'E'.
    ENDIF.

*> 저장위치
    LS_PR_BAPI_ITEM-STORE_LOC = LS_PRITEM-LGORT.

*> 요청 추적 번호
    LS_PR_BAPI_ITEM-TRACKINGNO = LS_PRITEM-BEDNR.

*> 자재 그룹
    LS_PR_BAPI_ITEM-MATL_GROUP = LS_PRITEM-MATKL.

*> 재고 운송 오더의 경우 공급(출고)플랜트
    LS_PR_BAPI_ITEM-SUPPL_PLNT = LS_PRITEM-RESWK.

*> 구매요청 수량
    LS_PR_BAPI_ITEM-QUANTITY = LS_PRITEM-BAMNG.

*> 구매요청 단위
    _G_CONV_DATA_EAI_TO_SAP LS_PRITEM-BAMEI '' LS_PR_BAPI_ITEM-UNIT.

    "ISO 단위는 수량 단위와 동일하게...
    IF NOT LS_PR_BAPI_ITEM-UNIT IS INITIAL.
      LS_PR_BAPI_ITEM-PREQ_UNIT_ISO = LS_PR_BAPI_ITEM-UNIT.
    ENDIF.

*> 요청일
    LS_PR_BAPI_ITEM-PREQ_DATE = LS_PRITEM-BADAT.

*> 납품일 범주
    LS_PR_BAPI_ITEM-DEL_DATCAT_EXT = LS_PRITEM-LPEIN.

*> 품목압품일
    LS_PR_BAPI_ITEM-DELIV_DATE = LS_PRITEM-EINDT.

*> 구매 요청 릴리즈일
    LS_PR_BAPI_ITEM-REL_DATE = LS_PRITEM-FRGDT.

*> 입고소요일수 (일)
    LS_PR_BAPI_ITEM-GR_PR_TIME = LS_PRITEM-WEBAZ.

*> 추정 가격
    LS_PR_BAPI_ITEM-PREQ_PRICE = LS_PRITEM-PREIS.

*> 가격단위
    LS_PR_BAPI_ITEM-PRICE_UNIT = LS_PRITEM-EPEIN.

*> 구매 문서의 품목 범주
    LS_PR_BAPI_ITEM-ITEM_CAT = LS_PRITEM-PSTYP.

*> 구매 문서의 품목 범주
    LS_PR_BAPI_ITEM-ACCTASSCAT = LS_PRITEM-KNTTP.

*> 복수 계정 지정에 대한 분재 지시자
    LS_PR_BAPI_ITEM-DISTRIB = LS_PRITEM-VRTKZ.

*> 분할 송장 지시자
    LS_PR_BAPI_ITEM-PART_INV = LS_PRITEM-TWRKZ.

*> 입고 지시자
    LS_PR_BAPI_ITEM-GR_IND = LS_PRITEM-WEPOS.

*> 비평가 입고
    LS_PR_BAPI_ITEM-GR_NON_VAL = LS_PRITEM-WEUNB.

*> 송장 수령 지시자
    LS_PR_BAPI_ITEM-IR_IND = LS_PRITEM-REPOS.

*> 희망 공급업체
    IF NOT LS_PRITEM-WLIEF IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_PRITEM-WLIEF
        IMPORTING
          OUTPUT = LS_PR_BAPI_ITEM-DES_VENDOR.
    ENDIF.

*> 고정 공급업체
    IF NOT LS_PRITEM-FLIEF IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_PRITEM-FLIEF
        IMPORTING
          OUTPUT = LS_PR_BAPI_ITEM-FIXED_VEND.
    ENDIF.

*> 구매 조직
    LS_PR_BAPI_ITEM-PURCH_ORG = LS_PRITEM-EKORG.

*> 평가 유형
    LS_PR_BAPI_ITEM-VAL_TYPE = LS_PRITEM-BWTAR.

*> 구매요청 마감
    LS_PR_BAPI_ITEM-CLOSED = LS_PRITEM-EBAKZ.

*> 고정된 구매 요청
    LS_PR_BAPI_ITEM-FIXED = LS_PRITEM-BAFIX.

*> 구매 오더 단위
    LS_PR_BAPI_ITEM-PO_UNIT = LS_PRITEM-BSTME.
    IF NOT LS_PR_BAPI_ITEM-PO_UNIT IS INITIAL.
      LS_PR_BAPI_ITEM-PO_UNIT_ISO = LS_PR_BAPI_ITEM-PO_UNIT.
    ENDIF.

*> 약정 항목
    LS_PR_BAPI_ITEM-CMMT_ITEM = LS_PRITEM-FIPOS.

*> 자금 관리 센터
    LS_PR_BAPI_ITEM-FUNDS_CTR = LS_PRITEM-FISTL.

*> 고객
    IF NOT LS_PRITEM-KUNNR IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_PRITEM-KUNNR
        IMPORTING
          OUTPUT = LS_PR_BAPI_ITEM-CUSTOMER.
    ENDIF.

*> 외주 공급업체
    IF NOT LS_PRITEM-EMLIF IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_PRITEM-EMLIF
        IMPORTING
          OUTPUT = LS_PR_BAPI_ITEM-SUPP_VENDOR.
    ENDIF.

*> SC 업체
    IF NOT LS_PRITEM-LBLKZ IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_PRITEM-LBLKZ
        IMPORTING
          OUTPUT = LS_PR_BAPI_ITEM-SC_VENDOR.
    ENDIF.

*> 특별재고평가
    LS_PR_BAPI_ITEM-VALUATION_SPEC_STOCK = LS_PRITEM-KZBWS.

*> 통화키
    LS_PR_BAPI_ITEM-CURRENCY = LS_PRITEM-WAERS.
    IF NOT LS_PR_BAPI_ITEM-CURRENCY IS INITIAL.
      LS_PR_BAPI_ITEM-CURRENCY_ISO = LS_PR_BAPI_ITEM-CURRENCY.
    ENDIF.

*> 계획 납품 소요 시간(일)
    LS_PR_BAPI_ITEM-PLND_DELRY = LS_PRITEM-PLIFZ.

    APPEND LS_PR_BAPI_ITEM TO ET_PR_BAPI_ITEM.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_itemx_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*&      --> IT_PRITEMX
*&      --> LT_PR_BAPI_ITEMX
*&---------------------------------------------------------------------*
FORM SET_ITEMX_DATA TABLES IT_PRITEMX STRUCTURE ZSMM_PRITEMX
                              ET_PR_BAPI_ITEMX STRUCTURE BAPIMEREQITEMX.

  DATA: LS_PR_BAPI_ITEMX TYPE BAPIMEREQITEMX,
        LV_ITEM_NO       TYPE BNFPO.

  CLEAR ET_PR_BAPI_ITEMX.
  LOOP AT IT_PRITEMX INTO DATA(LS_PRITEMX).
    CLEAR: LS_PR_BAPI_ITEMX.

*> 구매 요청 품목 번호
    IF NOT LS_PRITEMX-BNFPO IS INITIAL.
      LS_PR_BAPI_ITEMX-PREQ_ITEM = LS_PRITEMX-BNFPO.
      LV_ITEM_NO = LS_PRITEMX-BNFPO.
    ELSE.
      MESSAGE S017(ZMM01) WITH GC_BNFPO_TXT.
      PERFORM SET_RETURN_MSG USING 'E'.
      CONTINUE.
    ENDIF.

*> 구매그룹
    LS_PR_BAPI_ITEMX-PUR_GROUP = LS_PRITEMX-EKGRP.

*> 요청자 이름
    LS_PR_BAPI_ITEMX-PREQ_NAME = LS_PRITEMX-AFNAM.

*> 내역
    LS_PR_BAPI_ITEMX-SHORT_TEXT = LS_PRITEMX-TXZ01.

*> 자재번호
    LS_PR_BAPI_ITEMX-MATERIAL_LONG = LS_PRITEMX-MATNR.

*> 플랜트
    LS_PR_BAPI_ITEMX-PLANT = LS_PRITEMX-WERKS.

*> 저장위치
    LS_PR_BAPI_ITEMX-STORE_LOC = LS_PRITEMX-LGORT.

*> 요청 추적 번호
    LS_PR_BAPI_ITEMX-TRACKINGNO = LS_PRITEMX-BEDNR.

*> 자재 그룹
    LS_PR_BAPI_ITEMX-MATL_GROUP = LS_PRITEMX-MATKL.

*> 재고 운송 오더의 경우 공급(출고)플랜트
    LS_PR_BAPI_ITEMX-SUPPL_PLNT = LS_PRITEMX-RESWK.

*> 구매요청 수량
    LS_PR_BAPI_ITEMX-QUANTITY = LS_PRITEMX-BAMNG.

*> 구매요청 단위
    LS_PR_BAPI_ITEMX-UNIT = LS_PRITEMX-BAMEI.

    "ISO 단위는 수량 단위와 동일하게...
    IF NOT LS_PR_BAPI_ITEMX-UNIT IS INITIAL.
      LS_PR_BAPI_ITEMX-PREQ_UNIT_ISO = LS_PR_BAPI_ITEMX-UNIT.
    ENDIF.

*> 요청일
    LS_PR_BAPI_ITEMX-PREQ_DATE = LS_PRITEMX-BADAT.

*> 납품일 범주
    LS_PR_BAPI_ITEMX-DEL_DATCAT_EXT = LS_PRITEMX-LPEIN.

*> 품목압품일
    LS_PR_BAPI_ITEMX-DELIV_DATE = LS_PRITEMX-EINDT.

*> 구매 요청 릴리즈일
    LS_PR_BAPI_ITEMX-REL_DATE = LS_PRITEMX-FRGDT.

*> 입고소요일수 (일)
    LS_PR_BAPI_ITEMX-GR_PR_TIME = LS_PRITEMX-WEBAZ.

*> 추정 가격
    LS_PR_BAPI_ITEMX-PREQ_PRICE = LS_PRITEMX-PREIS.

*> 가격단위
    LS_PR_BAPI_ITEMX-PRICE_UNIT = LS_PRITEMX-EPEIN.

*> 구매 문서의 품목 범주
    LS_PR_BAPI_ITEMX-ITEM_CAT = LS_PRITEMX-PSTYP.

*> 구매 문서의 품목 범주
    LS_PR_BAPI_ITEMX-ACCTASSCAT = LS_PRITEMX-KNTTP.

*> 복수 계정 지정에 대한 분재 지시자
    LS_PR_BAPI_ITEMX-DISTRIB = LS_PRITEMX-VRTKZ.

*> 분할 송장 지시자
    LS_PR_BAPI_ITEMX-PART_INV = LS_PRITEMX-TWRKZ.

*> 입고 지시자
    LS_PR_BAPI_ITEMX-GR_IND = LS_PRITEMX-WEPOS.

*> 비평가 입고
    LS_PR_BAPI_ITEMX-GR_NON_VAL = LS_PRITEMX-WEUNB.

*> 송장 수령 지시자
    LS_PR_BAPI_ITEMX-IR_IND = LS_PRITEMX-REPOS.

*> 희망 공급업체
    LS_PR_BAPI_ITEMX-DES_VENDOR = LS_PRITEMX-WLIEF.

*> 고정 공급업체
    LS_PR_BAPI_ITEMX-FIXED_VEND = LS_PRITEMX-FLIEF.

*> 구매 조직
    LS_PR_BAPI_ITEMX-PURCH_ORG = LS_PRITEMX-EKORG.

*> 평가 유형
    LS_PR_BAPI_ITEMX-VAL_TYPE = LS_PRITEMX-BWTAR.

*> 구매요청 마감
    LS_PR_BAPI_ITEMX-CLOSED = LS_PRITEMX-EBAKZ.

*> 고정된 구매 요청
    LS_PR_BAPI_ITEMX-FIXED = LS_PRITEMX-BAFIX.

*> 구매 오더 단위
    LS_PR_BAPI_ITEMX-PO_UNIT = LS_PRITEMX-BSTME.
    IF NOT LS_PR_BAPI_ITEMX-PO_UNIT IS INITIAL.
      LS_PR_BAPI_ITEMX-PO_UNIT_ISO = LS_PR_BAPI_ITEMX-PO_UNIT.
    ENDIF.

*> 약정 항목
    LS_PR_BAPI_ITEMX-CMMT_ITEM = LS_PRITEMX-FIPOS.

*> 자금 관리 센터
    LS_PR_BAPI_ITEMX-FUNDS_CTR = LS_PRITEMX-FISTL.

*> 고객
    LS_PR_BAPI_ITEMX-CUSTOMER = LS_PRITEMX-KUNNR.

*> 외주 공급업체
    LS_PR_BAPI_ITEMX-SUPP_VENDOR = LS_PRITEMX-EMLIF.

*> SC 업체
    LS_PR_BAPI_ITEMX-SC_VENDOR = LS_PRITEMX-LBLKZ.

*> 특별재고평가
    LS_PR_BAPI_ITEMX-VALUATION_SPEC_STOCK = LS_PRITEMX-KZBWS.

*> 통화키
    LS_PR_BAPI_ITEMX-CURRENCY = LS_PRITEMX-WAERS.
    IF NOT LS_PR_BAPI_ITEMX-CURRENCY IS INITIAL.
      LS_PR_BAPI_ITEMX-CURRENCY_ISO = LS_PR_BAPI_ITEMX-CURRENCY.
    ENDIF.

*> 계획 납품 소요 시간(일)
    LS_PR_BAPI_ITEMX-PLND_DELRY = LS_PRITEMX-PLIFZ.

    APPEND LS_PR_BAPI_ITEMX TO ET_PR_BAPI_ITEMX.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_account_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_ACCOUNT_DATA TABLES IT_PRACCOUNT STRUCTURE ZSMM_PRACCOUNT
                                ET_PR_BAPI_ACC STRUCTURE BAPIMEREQACCOUNT.

  DATA: LS_PR_BAPI_ACC TYPE BAPIMEREQACCOUNT,
        LV_ITEM_NO     TYPE BNFPO.

  CLEAR ET_PR_BAPI_ACC.
  LOOP AT IT_PRACCOUNT INTO DATA(LS_PRACCOUNT).
    CLEAR LS_PR_BAPI_ACC.

*> 구매 요청 품목 번호
    IF NOT LS_PRACCOUNT-BNFPO IS INITIAL.
      LS_PR_BAPI_ACC-PREQ_ITEM = LS_PRACCOUNT-BNFPO.
      LV_ITEM_NO = LS_PR_BAPI_ACC-PREQ_ITEM.
    ELSE.
      LV_ITEM_NO = SY-TABIX.
    ENDIF.


*> 계정 지정 순번
    LS_PR_BAPI_ACC-SERIAL_NO = LS_PRACCOUNT-ZEBKN.

*> 수량
    LS_PR_BAPI_ACC-QUANTITY = LS_PRACCOUNT-MENGE.

*> 다중 계정 지정의 경우 분배 백분율
    LS_PR_BAPI_ACC-DISTR_PERC = LS_PRACCOUNT-VPROZ.

*> BAPI에 대한 통화금액
    LS_PR_BAPI_ACC-NET_VALUE = LS_PRACCOUNT-BAPICUREXT.

*> G/L 계정 번호
    IF NOT LS_PRACCOUNT-SAKNR IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_PRACCOUNT-SAKNR
        IMPORTING
          OUTPUT = LS_PR_BAPI_ACC-GL_ACCOUNT.
    ENDIF.

*> 사업 영역
    LS_PR_BAPI_ACC-BUS_AREA = LS_PRACCOUNT-GSBER.

*> 코스트센터
    LS_PR_BAPI_ACC-COSTCENTER = LS_PRACCOUNT-KOSTL.

*> 주요 자산 번호
    LS_PR_BAPI_ACC-ASSET_NO = LS_PRACCOUNT-ANLN1.

*> 자산 하위 번호
    LS_PR_BAPI_ACC-SUB_NUMBER = LS_PRACCOUNT-ANLN2.

*> 오더 번호
    LS_PR_BAPI_ACC-ORDERID = LS_PRACCOUNT-AUFNR.

*> 손익 센터
    LS_PR_BAPI_ACC-PROFIT_CTR = LS_PRACCOUNT-PRCTR.

*> 작업 분석 구조요소(WBS 요소)
    IF NOT LS_PRACCOUNT-PS_POSID IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_ABPSN_INPUT'
        EXPORTING
          INPUT  = LS_PRACCOUNT-PS_POSID
        IMPORTING
          OUTPUT = LS_PR_BAPI_ACC-WBS_ELEMENT.
    ENDIF.

*> 계정지정 네트워크번호
    LS_PR_BAPI_ACC-NETWORK = LS_PRACCOUNT-NPLNR.

*> 약정 항목
    LS_PR_BAPI_ACC-CMMT_ITEM = LS_PRACCOUNT-FIPOS.

*> 자금 관리 센터
    LS_PR_BAPI_ACC-FUNDS_CTR = LS_PRACCOUNT-FISTL.

    APPEND LS_PR_BAPI_ACC TO ET_PR_BAPI_ACC.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_accountX_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_ACCOUNTX_DATA TABLES IT_PRACCOUNTX STRUCTURE ZSMM_PRACCOUNTX
                                 ET_PR_BAPI_ACCX STRUCTURE BAPIMEREQACCOUNTX.

  DATA: LS_PR_BAPI_ACCX TYPE BAPIMEREQACCOUNTX,
        LV_ITEM_NO      TYPE BNFPO.

  CLEAR ET_PR_BAPI_ACCX.
  LOOP AT IT_PRACCOUNTX INTO DATA(LS_PRACCOUNTX).
    CLEAR LS_PR_BAPI_ACCX.

*> 구매 요청 품목 번호
    IF NOT LS_PRACCOUNTX-BNFPO IS INITIAL.
      LS_PR_BAPI_ACCX-PREQ_ITEM = LS_PRACCOUNTX-BNFPO.
      LV_ITEM_NO = LS_PR_BAPI_ACCX-PREQ_ITEM.
    ELSE.
      LV_ITEM_NO = SY-TABIX.
    ENDIF.


*> 계정 지정 순번
    LS_PR_BAPI_ACCX-SERIAL_NO = LS_PRACCOUNTX-ZEBKN.

*> 수량
    LS_PR_BAPI_ACCX-QUANTITY = LS_PRACCOUNTX-MENGE.

*> 다중 계정 지정의 경우 분배 백분율
    LS_PR_BAPI_ACCX-DISTR_PERC = LS_PRACCOUNTX-VPROZ.

*> BAPI에 대한 통화금액
    LS_PR_BAPI_ACCX-NET_VALUE = LS_PRACCOUNTX-BAPICUREXT.

*> G/L 계정 번호
    LS_PR_BAPI_ACCX-GL_ACCOUNT = LS_PRACCOUNTX-SAKNR.

*> 사업 영역
    LS_PR_BAPI_ACCX-BUS_AREA = LS_PRACCOUNTX-GSBER.

*> 코스트센터
    LS_PR_BAPI_ACCX-COSTCENTER = LS_PRACCOUNTX-KOSTL.

*> 주요 자산 번호
    LS_PR_BAPI_ACCX-ASSET_NO = LS_PRACCOUNTX-ANLN1.

*> 자산 하위 번호
    LS_PR_BAPI_ACCX-SUB_NUMBER = LS_PRACCOUNTX-ANLN2.

*> 오더 번호
    LS_PR_BAPI_ACCX-ORDERID = LS_PRACCOUNTX-AUFNR.

*> 손익 센터
    LS_PR_BAPI_ACCX-PROFIT_CTR = LS_PRACCOUNTX-PRCTR.

*> 작업 분석 구조요소(WBS 요소)
    LS_PR_BAPI_ACCX-WBS_ELEMENT = LS_PRACCOUNTX-PS_POSID.

*> 계정지정 네트워크번호
    LS_PR_BAPI_ACCX-NETWORK = LS_PRACCOUNTX-NPLNR.

*> 약정 항목
    LS_PR_BAPI_ACCX-CMMT_ITEM = LS_PRACCOUNTX-FIPOS.

*> 자금 관리 센터
    LS_PR_BAPI_ACCX-FUNDS_CTR = LS_PRACCOUNTX-FISTL.

    APPEND LS_PR_BAPI_ACCX TO ET_PR_BAPI_ACCX.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_delivery_addr
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_DELIVERY_ADDR TABLES IT_PRADDRDELIVERY STRUCTURE ZSMM_PRADDRDELIVERY
                                 ET_PR_BAPI_DEL_ADDR STRUCTURE BAPIMERQADDRDELIVERY.

  DATA: LS_PR_BAPI_DEL_ADDR TYPE BAPIMERQADDRDELIVERY,
        LV_ITEM_NO          TYPE BNFPO.

  CLEAR ET_PR_BAPI_DEL_ADDR.
  LOOP AT IT_PRADDRDELIVERY INTO DATA(LS_PRADDRDELIVERY).
    CLEAR LS_PR_BAPI_DEL_ADDR.

*> 구매 요청 품목 번호
    IF NOT LS_PRADDRDELIVERY-BNFPO IS INITIAL.
      LS_PR_BAPI_DEL_ADDR-PREQ_ITEM = LS_PRADDRDELIVERY-BNFPO.
      LV_ITEM_NO = LS_PR_BAPI_DEL_ADDR-PREQ_ITEM.
    ELSE.
      LV_ITEM_NO = SY-TABIX.
    ENDIF.


*> 구매 요청 번호
    LS_PR_BAPI_DEL_ADDR-PREQ_NO = LS_PRADDRDELIVERY-BANFN.

*> 구매 요청 품목 번호
    LS_PR_BAPI_DEL_ADDR-PREQ_ITEM = LS_PRADDRDELIVERY-BNFPO.

*> 이름1
    LS_PR_BAPI_DEL_ADDR-NAME = LS_PRADDRDELIVERY-NAME1.

*> 이름2
    LS_PR_BAPI_DEL_ADDR-NAME_2 = LS_PRADDRDELIVERY-NAME2.

*> 상세주소
    LS_PR_BAPI_DEL_ADDR-STREET = LS_PRADDRDELIVERY-STREET.

*> 번지
    LS_PR_BAPI_DEL_ADDR-HOUSE_NO = LS_PRADDRDELIVERY-HOUSE_NUM1.

*> 도시
    LS_PR_BAPI_DEL_ADDR-CITY = LS_PRADDRDELIVERY-CITY1.

*> 국가
    LS_PR_BAPI_DEL_ADDR-COUNTRY = LS_PRADDRDELIVERY-LAND1.

*> 우편번호
    LS_PR_BAPI_DEL_ADDR-POSTL_COD1 = LS_PRADDRDELIVERY-POST_CD.

    APPEND LS_PR_BAPI_DEL_ADDR TO ET_PR_BAPI_DEL_ADDR.
  ENDLOOP.


ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_extension
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_EXTENSION TABLES IT_PRITEM STRUCTURE ZSMM_PRITEM
                             IT_PRITEMX STRUCTURE ZSMM_PRITEMX
                             ET_PR_BAPI_EXTENSIONIN STRUCTURE BAPIPAREX.

  DATA: LS_CI_EBANDB           TYPE BAPI_TE_MEREQITEM,
        LS_CI_EBANDBX          TYPE BAPI_TE_MEREQITEMX,
        LS_PR_BAPI_EXTENSIONIN TYPE BAPIPAREX.

  CONSTANTS: LC_EXT_STR_NAME  TYPE BAPIPAREX-STRUCTURE VALUE 'BAPI_TE_MEREQITEM',
             LC_EXTX_STR_NAME TYPE BAPIPAREX-STRUCTURE VALUE 'BAPI_TE_MEREQITEMX'.

  CLEAR ET_PR_BAPI_EXTENSIONIN.

  LOOP AT IT_PRITEM INTO DATA(LS_PRITEM).
    CLEAR: LS_CI_EBANDB, LS_PR_BAPI_EXTENSIONIN.
    LS_CI_EBANDB-PREQ_ITEM = LS_PRITEM-BNFPO.
*    LS_CI_EBANDB-ZORDER_PERSON = LS_PRITEM-ZORDER_PERSON.
*    LS_CI_EBANDB-ZORDER_DEPARTMENT = LS_PRITEM-ZORDER_DEPARTMENT.
*    LS_CI_EBANDB-ZMRO_CATEGORY = LS_PRITEM-ZMRO_CATEGORY.
*    LS_CI_EBANDB-ZMARKET_ID = LS_PRITEM-ZMARKET_ID.
*    LS_CI_EBANDB-ZSTARTDATE = LS_PRITEM-ZSTARTDATE.
*    LS_CI_EBANDB-ZENDDATE = LS_PRITEM-ZENDDATE.
    LS_PR_BAPI_EXTENSIONIN-STRUCTURE = LC_EXT_STR_NAME.

    PERFORM TRANSFER_TO_EXTENSIONIN USING LS_CI_EBANDB CHANGING LS_PR_BAPI_EXTENSIONIN.
    APPEND LS_PR_BAPI_EXTENSIONIN TO ET_PR_BAPI_EXTENSIONIN.
  ENDLOOP.

*--------------------------------------------------------------------*

  LOOP AT IT_PRITEMX INTO DATA(LS_PRITEMX).
    CLEAR: LS_CI_EBANDBX, LS_PR_BAPI_EXTENSIONIN.
    LS_CI_EBANDBX-PREQ_ITEM = LS_PRITEMX-BNFPO.
*    LS_CI_EBANDBX-ZORDER_PERSON = LS_PRITEMX-ZORDER_PERSON.
*    LS_CI_EBANDBX-ZORDER_DEPARTMENT = LS_PRITEMX-ZORDER_DEPARTMENT.
*    LS_CI_EBANDBX-ZMRO_CATEGORY = LS_PRITEMX-ZMRO_CATEGORY.
*    LS_CI_EBANDBX-ZMARKET_ID = LS_PRITEMX-ZMARKET_ID.
*    LS_CI_EBANDBX-ZSTARTDATE = LS_PRITEMX-ZSTARTDATE.
*    LS_CI_EBANDBX-ZENDDATE = LS_PRITEMX-ZENDDATE.
    LS_PR_BAPI_EXTENSIONIN-STRUCTURE = LC_EXTX_STR_NAME.
    PERFORM TRANSFER_TO_EXTENSIONIN USING LS_CI_EBANDBX CHANGING LS_PR_BAPI_EXTENSIONIN.
    APPEND LS_PR_BAPI_EXTENSIONIN TO ET_PR_BAPI_EXTENSIONIN.
  ENDLOOP.


ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_components_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_COMPONENTS_DATA TABLES IT_PRCOMPONENTS STRUCTURE ZSMM_PRCOMPONENTS
                                   ET_PR_BAPI_COMPONENT STRUCTURE BAPIMEREQCOMPONENT.

  DATA: LS_PR_BAPI_COMPONENT TYPE BAPIMEREQCOMPONENT,
        LV_ITEM_NO           TYPE BNFPO.

  CLEAR ET_PR_BAPI_COMPONENT.
  LOOP AT IT_PRCOMPONENTS INTO DATA(LS_PRCOMPONENTS).
    CLEAR LS_PR_BAPI_COMPONENT.

*> 구매 요청 품목 번호
    IF NOT LS_PRCOMPONENTS-BNFPO IS INITIAL.
      LS_PR_BAPI_COMPONENT-PREQ_ITEM = LS_PRCOMPONENTS-BNFPO.
      LV_ITEM_NO = LS_PR_BAPI_COMPONENT-PREQ_ITEM.
    ELSE.
      LV_ITEM_NO = SY-TABIX.
    ENDIF.


*> 구매요청 품목번호
    LS_PR_BAPI_COMPONENT-PREQ_ITEM = LS_PRCOMPONENTS-BNFPO.

*> 예약/종속 소요량에 대한 품목 번호
    LS_PR_BAPI_COMPONENT-ITEM_NO = LS_PRCOMPONENTS-RSPOS.

*> 자재번호(18자)
    IF NOT LS_PRCOMPONENTS-MATNR IS INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
        EXPORTING
          INPUT        = LS_PRCOMPONENTS-MATNR
        IMPORTING
          OUTPUT       = LS_PR_BAPI_COMPONENT-MATERIAL
        EXCEPTIONS
          LENGTH_ERROR = 1
          OTHERS       = 2.

      IF SY-SUBRC NE 0.
        PERFORM SET_RETURN_MSG USING 'E'.
      ENDIF.
    ENDIF.

*> 구성폼목 소요량
    LS_PR_BAPI_COMPONENT-ENTRY_QUANTITY = LS_PRCOMPONENTS-CO_MENGE.

*> 입력단위
    LS_PR_BAPI_COMPONENT-ENTRY_UOM = LS_PRCOMPONENTS-ERFME.

*> 고정수량
    LS_PR_BAPI_COMPONENT-FIXED_QUAN = LS_PRCOMPONENTS-FMENG.

*> 플랜트
    LS_PR_BAPI_COMPONENT-PLANT = LS_PRCOMPONENTS-WERKS.

*> 구성부품 소요일
    LS_PR_BAPI_COMPONENT-REQ_DATE = LS_PRCOMPONENTS-BDTER.

*> 배치 번호
    LS_PR_BAPI_COMPONENT-BATCH = LS_PRCOMPONENTS-CHARG.

*> 출고 저장 장소
    LS_PR_BAPI_COMPONENT-ISS_ST_LOC = LS_PRCOMPONENTS-LGPRO.

*> 변경 유형룰
    LS_PR_BAPI_COMPONENT-CHANGE_ID = LS_PRCOMPONENTS-CHANGE_ID.

    APPEND LS_PR_BAPI_COMPONENT TO ET_PR_BAPI_COMPONENT.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form set_componentsx_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
FORM SET_COMPONENTSX_DATA TABLES IT_PRCOMPONENTSX STRUCTURE ZSMM_PRCOMPONENTSX
                                    ET_PR_BAPI_COMPONENTX STRUCTURE BAPIMEREQCOMPONENTX.

  DATA: LS_PR_BAPI_COMPONENTX TYPE BAPIMEREQCOMPONENTX,
        LV_ITEM_NO            TYPE BNFPO.

  CLEAR ET_PR_BAPI_COMPONENTX.
  LOOP AT IT_PRCOMPONENTSX INTO DATA(LS_PRCOMPONENTSX).
    CLEAR LS_PR_BAPI_COMPONENTX.

*> 구매 요청 품목 번호
    IF NOT LS_PRCOMPONENTSX-BNFPO IS INITIAL.
      LS_PR_BAPI_COMPONENTX-PREQ_ITEM = LS_PRCOMPONENTSX-BNFPO.
      LV_ITEM_NO = LS_PR_BAPI_COMPONENTX-PREQ_ITEM.
    ELSE.
      LV_ITEM_NO = SY-TABIX.
    ENDIF.


*> 구매요청 품목번호
    LS_PR_BAPI_COMPONENTX-PREQ_ITEM = LS_PRCOMPONENTSX-BNFPO.

*> 예약/종속 소요량에 대한 품목 번호
    LS_PR_BAPI_COMPONENTX-ITEM_NO = LS_PRCOMPONENTSX-RSPOS.

*> 자재번호(18자)
    LS_PR_BAPI_COMPONENTX-MATERIAL = LS_PRCOMPONENTSX-MATNR.

*> 구성폼목 소요량
    LS_PR_BAPI_COMPONENTX-ENTRY_QUANTITY = LS_PRCOMPONENTSX-CO_MENGE.

*> 입력단위
    LS_PR_BAPI_COMPONENTX-ENTRY_UOM = LS_PRCOMPONENTSX-ERFME.

*> 고정수량
    LS_PR_BAPI_COMPONENTX-FIXED_QUAN = LS_PRCOMPONENTSX-FMENG.

*> 플랜트
    LS_PR_BAPI_COMPONENTX-PLANT = LS_PRCOMPONENTSX-WERKS.

*> 구성부품 소요일
    LS_PR_BAPI_COMPONENTX-REQ_DATE = LS_PRCOMPONENTSX-BDTER.

*> 배치 번호
    LS_PR_BAPI_COMPONENTX-BATCH = LS_PRCOMPONENTSX-CHARG.

*> 출고 저장 장소
    LS_PR_BAPI_COMPONENTX-ISS_ST_LOC = LS_PRCOMPONENTSX-LGPRO.

*> 변경유형
    LS_PR_BAPI_COMPONENTX-CHANGE_ID = LS_PRCOMPONENTSX-CHANGE_ID.

    APPEND LS_PR_BAPI_COMPONENTX TO ET_PR_BAPI_COMPONENTX.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form save_cbo_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*&      --> IS_PRHEADER
*&---------------------------------------------------------------------*
FORM SAVE_CBO_DATA USING IV_BANFN
                             IS_PRHEADER TYPE ZSMM_PRHEADER
                             IS_PRHEADERX TYPE ZSMM_PRHEADERX
                    CHANGING EV_SUBRC.

  DATA: LS_ZTMM30010 LIKE ZTMM30010.

  LS_ZTMM30010-BANFN = IV_BANFN.

  IF IS_PRHEADERX-ZPRTITLE EQ 'X'.
    LS_ZTMM30010-ZPRTITLE = IS_PRHEADER-ZPRTITLE.
  ENDIF.

  IF IS_PRHEADERX-ZPEQ_DEPARTMENT EQ 'X'.
    LS_ZTMM30010-ZPEQ_DEPARTMENT = IS_PRHEADER-ZPEQ_DEPARTMENT.
  ENDIF.

  IF IS_PRHEADERX-ZREQUESTER EQ 'X'.
    LS_ZTMM30010-ZREQUESTER = IS_PRHEADER-ZREQUESTER.
  ENDIF.

  IF IS_PRHEADERX-ZNOPRICE EQ 'X'.
    LS_ZTMM30010-ZNOPRICE = IS_PRHEADER-ZNOPRICE.
  ENDIF.

  IF IS_PRHEADERX-ZURGENT EQ 'X'.
    LS_ZTMM30010-ZURGENT = IS_PRHEADER-ZURGENT.
  ENDIF.

  IF IS_PRHEADERX-ZPRE_INPUT EQ 'X'.
    LS_ZTMM30010-ZPRE_INPUT = IS_PRHEADER-ZPRE_INPUT.
  ENDIF.

  IF IS_PRHEADERX-ZURGENT_REASON EQ 'X'.
    LS_ZTMM30010-ZURGENT_REASON = IS_PRHEADER-ZURGENT_REASON.
  ENDIF.

  IF IS_PRHEADERX-ZPRE_INPUT_REASON EQ 'X'.
    LS_ZTMM30010-ZPRE_INPUT_REASON = IS_PRHEADER-ZPRE_INPUT_REASON.
  ENDIF.

  IF IS_PRHEADERX-ZRECEIPT EQ 'X'.
    LS_ZTMM30010-ZRECEIPT = IS_PRHEADER-ZRECEIPT.
  ENDIF.

  IF IS_PRHEADERX-ZSOURCE_SYS EQ 'X'.
    LS_ZTMM30010-ZSOURCE_SYS = IS_PRHEADER-ZSOURCE_SYS.
  ENDIF.

  LS_ZTMM30010-ERDAT = SY-DATUM.
  LS_ZTMM30010-ERZET = SY-UZEIT.
  LS_ZTMM30010-ERNAM = SY-UNAME.

  MODIFY ZTMM30010 FROM LS_ZTMM30010.

  EV_SUBRC = SY-SUBRC.

ENDFORM.
