*&---------------------------------------------------------------------*
*& Include          ZOMM5020SCR
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* SELECTION SCREEN
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.
  PARAMETERS P_BUKRS LIKE RBKP-BUKRS OBLIGATORY
                                      MEMORY ID BUK
                                      AS LISTBOX VISIBLE LENGTH 25
                                      MODIF ID MST.

  SELECT-OPTIONS:
  S_BUPLA FOR RBKP-BUPLA NO INTERVALS NO-EXTENSION , "사업장
  S_LIFNR FOR LFA1-LIFNR , "공급업체
  S_STCD2 FOR LFA1-STCD2 , "사업자번호
  S_WERKS FOR EKPO-WERKS , "플랜트
  S_EKGRP FOR EKKO-EKGRP, "구매그룹

  S_ORDER FOR EKKO-ZORDER_PERSON, "발주자
  S_ORDDP FOR EKKO-ZORDER_DEPARTMENT, "발주부서
  S_EXPPS FOR EKKO-ZEXPEN_PERSON, "지출발의 담당자
  S_EXPDP FOR EKKO-ZEXPEN_DEPARTMENT, "지출발의 부서

*  S_BLDAT FOR ZDTV3T_AP_EXT_D-BLDAT, "전자세금계산서 작성일자
  S_BUDAT FOR RBKP-BUDAT, "전기일자
  S_BELNR FOR RBKP-BELNR, "송장번호
  S_ERFNAM FOR RBKP-ERFNAM MODIF ID MST,  "송장처리자

*  S_ISUID FOR ZDTV3T_AP_HEAD-ISSUE_ID,  "전자세금계산서 승인번호
  S_MATNR FOR EKPO-MATNR.  "자재

SELECTION-SCREEN END OF BLOCK B1.


*-선택조건
SELECTION-SCREEN BEGIN OF BLOCK B5 WITH FRAME TITLE TEXT-T45.
  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_RP1 RADIOBUTTON GROUP RG2 DEFAULT 'X' USER-COMMAND R2.
    SELECTION-SCREEN COMMENT (15) TEXT-T46 FOR FIELD P_RP1. "물품일반

    SELECTION-SCREEN POSITION 20.
    PARAMETERS P_RP2 RADIOBUTTON GROUP RG2.
    SELECTION-SCREEN COMMENT (5) TEXT-T47 FOR FIELD P_RP2. "물품선급

    SELECTION-SCREEN POSITION 33.
    PARAMETERS P_RP3 RADIOBUTTON GROUP RG2 MODIF ID RP3.
    SELECTION-SCREEN COMMENT (15) TEXT-T48 FOR FIELD P_RP3. "자율납품&위탁정산

    SELECTION-SCREEN POSITION 53.
    PARAMETERS P_RP4 RADIOBUTTON GROUP RG2.
    SELECTION-SCREEN COMMENT (5) TEXT-T49 FOR FIELD P_RP4. "공사용역

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B5.

*-세금계산서 작성방법
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.
  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' "정발행
                    MODIF ID PYT USER-COMMAND R4.
    SELECTION-SCREEN COMMENT (5) TEXT-T05 FOR FIELD P_R1.

    SELECTION-SCREEN POSITION 33.
    PARAMETERS P_R2 RADIOBUTTON GROUP R1 MODIF ID PYT. "역발행
    SELECTION-SCREEN COMMENT (5) TEXT-T06 FOR FIELD P_R2.

  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B2.
