*&---------------------------------------------------------------------*
*& Include          ZOMM5010SCR
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* Selection-screen
*----------------------------------------------------------------------*
*-조회조건
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.
*  PARAMETERS: P_BUKRS TYPE T001-BUKRS OBLIGATORY
*                                      MEMORY ID BUK
*                                      AS LISTBOX VISIBLE LENGTH 25
*                                      MODIF ID MST.

  PARAMETERS: P_BUKRS TYPE T001-BUKRS OBLIGATORY.

  SELECT-OPTIONS:
     S_LIFNR FOR EKKO-LIFNR, "공급업체
     S_STCD2 FOR LFA1-STCD2, "사업자번호
     S_ORDPS FOR EKKO-ZORDER_PERSON , "발주자
     S_ORDDP FOR EKKO-ZORDER_DEPARTMENT MODIF ID MST, "발주부서
     S_EXPPS FOR EKKO-ZEXPEN_PERSON , "지출발의 담당자
     S_EXPDP FOR EKKO-ZEXPEN_DEPARTMENT MODIF ID MST, "지출발의 부서
     S_EKORG FOR EKKO-EKORG, "구매조직
     S_EKGRP FOR EKKO-EKGRP, "구매그룹

     S_TAXIM FOR MLAN-TAXIM, "세금지시자
     S_BUPLA FOR RBKP-BUPLA, "사업장
     S_WERKS FOR EKBE-WERKS, "플랜트
     S_MATNR FOR EKBE-MATNR, "자재번호
     S_MATKL FOR EKPO-MATKL, "자재그룹
     S_EBELN FOR EKBE-EBELN, "구매오더 번호
     S_BELNR FOR EKBE-BELNR, "입고 번호
     S_XBLNR FOR EKBE-XBLNR, "납품 번호
     S_BSART FOR EKKO-BSART, "구매문서 유형
     S_BUDAT FOR EKBE-BUDAT OBLIGATORY. "입고 일자
SELECTION-SCREEN END OF BLOCK B1.

*-선택조건
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-T03.
  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_RP1 RADIOBUTTON GROUP RG2 DEFAULT 'X' USER-COMMAND R2.
    SELECTION-SCREEN COMMENT (15) TEXT-T12 FOR FIELD P_RP1. "물품일반

    SELECTION-SCREEN POSITION 20.
    PARAMETERS P_RP2 RADIOBUTTON GROUP RG2.
    SELECTION-SCREEN COMMENT (5) TEXT-T14 FOR FIELD P_RP2. "물품선급

    SELECTION-SCREEN POSITION 33.
    PARAMETERS P_RP3 RADIOBUTTON GROUP RG2 MODIF ID RP3.
    SELECTION-SCREEN COMMENT (15) TEXT-T15 FOR FIELD P_RP3. "자율납품&위탁정산

    SELECTION-SCREEN POSITION 53.
    PARAMETERS P_RP4 RADIOBUTTON GROUP RG2.
    SELECTION-SCREEN COMMENT (5) TEXT-T13 FOR FIELD P_RP4. "공사용역

  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B3.

*-세금계산서 작성방법
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.
  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_R1 RADIOBUTTON GROUP RG1 DEFAULT 'X'  "정발행
                    MODIF ID PYT  USER-COMMAND R4.
    SELECTION-SCREEN COMMENT (5) TEXT-T10 FOR FIELD P_R1.

    SELECTION-SCREEN POSITION 33.
    PARAMETERS P_R2 RADIOBUTTON GROUP RG1 MODIF ID PYT. "역발행
    SELECTION-SCREEN COMMENT (5) TEXT-T11 FOR FIELD P_R2.

  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B2.


*-송장처리 통화
SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME TITLE TEXT-T04.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS P_R11 RADIOBUTTON GROUP RG3 DEFAULT 'X' MODIF ID CUR USER-COMMAND R3.
    SELECTION-SCREEN COMMENT (25) TEXT-T18 FOR FIELD P_R11. "원화
    SELECTION-SCREEN POSITION 33.
    PARAMETERS P_R12 RADIOBUTTON GROUP RG3 MODIF ID CUR.
    SELECTION-SCREEN COMMENT (5) TEXT-T19 FOR FIELD P_R12. "외화
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B4.
