*&---------------------------------------------------------------------*
*& Include          ZRMM4410TOP
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------------
* 주의:ALV Display Table은 반드시 Types 선언으로 해주세요
*      인터널 테이블은 Header Line Table 금지
*-----------------------------------------------------------------------------
TABLES: T001, T001W, T001L, LFA1, MARA, MCH1.


*----------------------------------------------------------------------*
* Local Class Define..
*----------------------------------------------------------------------*
CLASS : LCL_CUST_ALV_GRID DEFINITION DEFERRED.

*----------------------------------------------------------------------*
* Constants
*----------------------------------------------------------------------*

CONSTANTS: GC_BT(2) VALUE 'BT',
           GC_EQ(2)     VALUE 'EQ',
           GC_3101(4)   VALUE '3101',
           GC_3002(4)   VALUE '3002',
           GC_1000(4)   VALUE '1000',

           GC_BUKRS(7)  VALUE 'P_BUKRS',
           GC_WERKS(7)  VALUE 'S_WERKS',
           GC_LGORT(7)  VALUE 'S_LGORT',

           GC_GR_321(6) VALUE 'GR_321',
           GC_GI_322(6) VALUE 'GI_322',
           GC_GI_ETC(6) VALUE 'GI_ETC',
           GC_GI_PRD(6) VALUE 'GI_PRD',

           GC_C100(10)  VALUE 'C100',
           GC_C110(10)  VALUE 'C110',
           GC_C200(10)  VALUE 'C200',
           GC_C201(10)  VALUE 'C201',
           GC_C210(10)  VALUE 'C210',
           GC_C300(10)  VALUE 'C300',
           GC_C310(10)  VALUE 'C310',
           GC_C400(10)  VALUE 'C400',
           GC_C401(10)  VALUE 'C401',
           GC_C500(10)  VALUE 'C500',
           GC_C510(10)  VALUE 'C510',
           GC_C600(10)  VALUE 'C600',
           GC_C601(10)  VALUE 'C601',
           GC_C610(10)  VALUE 'C610',
           GC_C700(10)  VALUE 'C700',
           GC_C701(10)  VALUE 'C701',
           GC_C710(10)  VALUE 'C710',

           GC_FORMNAME  TYPE TDSFNAME VALUE 'ZSMM_FORM_003'.

*----------------------------------------------------------------------*
* Type
*----------------------------------------------------------------------*
TYPES: BEGIN OF TY_DATA,
         BUKRS           TYPE ZCCMMESTOCKREP-BUKRS,
         WERKS           TYPE ZCCMMESTOCKREP-WERKS,
         NAME1           TYPE ZCCMMESTOCKREP-NAME1,
         LGORT           TYPE ZCCMMESTOCKREP-LGORT,
         LGOBE           TYPE ZCCMMESTOCKREP-LGOBE,
         LIFNR           TYPE ZCCMMESTOCKREP-LIFNR,
         NAME2           TYPE ZCCMMESTOCKREP-NAME2,
         MATNR           TYPE ZCCMMESTOCKREP-MATNR,
         MAKTX           TYPE MAKT-MAKTX,
         MATKL           TYPE ZCCMMESTOCKREP-MATKL,
         WGBEZ           TYPE T023T-WGBEZ,
         CHARG           TYPE ZCCMMESTOCKREP-CHARG,
         BWTAR           TYPE ZCCMMESTOCKREP-BWTAR,
*         LBBSA_SID       TYPE ZCCMMESTOCKREP-LBBSA_SID,
*         BSTAUS_SG       TYPE ZCCMMESTOCKREP-BSTAUS_SG,
         INITSTOCK       TYPE ZCCMMESTOCKREP-INITSTOCK,
         INITSTOCK_VAL   TYPE ZCCMMESTOCKREP-INITSTOCK_VAL,
         INITQISTOCK     TYPE ZCCMMESTOCKREP-INITQISTOCK,
         INITQISTOCK_VAL TYPE ZCCMMESTOCKREP-INITQISTOCK_VAL,
         INITBLSTOCK     TYPE ZCCMMESTOCKREP-INITBLSTOCK,
         INITBLSTOCK_VAL TYPE ZCCMMESTOCKREP-INITBLSTOCK_VAL,
         TRSTOCKSLQTY    TYPE ZCCMMESTOCKREP-TRSTOCKSLQTY,
         TRSTOCKSLVALUE  TYPE ZCCMMESTOCKREP-TRSTOCKSLVALUE,
         TRSTOCKPLQTY    TYPE ZCCMMESTOCKREP-TRSTOCKPLQTY,
         TRSTOCKPLVALUE  TYPE ZCCMMESTOCKREP-TRSTOCKPLVALUE,
         SITQTY          TYPE ZCCMMESTOCKREP-SITQTY,
         SITVALUE        TYPE ZCCMMESTOCKREP-SITVALUE,

         GR_PUR_QTY_UN   TYPE ZCCMMESTOCKREP-GR_PUR_QTY_UN,
         GR_PUR_QTY_QI   TYPE ZCCMMESTOCKREP-GR_PUR_QTY_QI,
         GR_PUR_QTY_BL   TYPE ZCCMMESTOCKREP-GR_PUR_QTY_BL,

         GR_PRD_QTY_UN   TYPE ZCCMMESTOCKREP-GR_PRD_QTY_UN,
         GR_PRD_QTY_QI   TYPE ZCCMMESTOCKREP-GR_PRD_QTY_QI,
         GR_PRD_QTY_BL   TYPE ZCCMMESTOCKREP-GR_PRD_QTY_BL,

         GR_DSC_QTY_UN   TYPE ZCCMMESTOCKREP-GR_DSC_QTY_UN,
         GR_DSC_QTY_QI   TYPE ZCCMMESTOCKREP-GR_DSC_QTY_QI,
         GR_DSC_QTY_BL   TYPE ZCCMMESTOCKREP-GR_DSC_QTY_BL,

         GR_STO_QTY_UN   TYPE ZCCMMESTOCKREP-GR_STO_QTY_UN,
         GR_STO_QTY_QI   TYPE ZCCMMESTOCKREP-GR_STO_QTY_QI,
         GR_STO_QTY_BL   TYPE ZCCMMESTOCKREP-GR_STO_QTY_BL,
         GR_STO_QTY_ST   TYPE ZCCMMESTOCKREP-GR_STO_QTY_ST,

         GR_SL_QTY_UN    TYPE ZCCMMESTOCKREP-GR_SL_QTY_UN,
         GR_SL_QTY_QI    TYPE ZCCMMESTOCKREP-GR_SL_QTY_QI,
         GR_SL_QTY_BL    TYPE ZCCMMESTOCKREP-GR_SL_QTY_BL,

         GR_ETC_QTY_UN   TYPE ZCCMMESTOCKREP-GR_ETC_QTY_UN,
         GR_ETC_QTY_QI   TYPE ZCCMMESTOCKREP-GR_ETC_QTY_QI,
         GR_ETC_QTY_BL   TYPE ZCCMMESTOCKREP-GR_ETC_QTY_BL,

         GR_TR_QTY_UN    TYPE ZCCMMESTOCKREP-GR_TR_QTY_UN,
         GR_TR_QTY_QI    TYPE ZCCMMESTOCKREP-GR_TR_QTY_QI,
         GR_TR_QTY_BL    TYPE ZCCMMESTOCKREP-GR_TR_QTY_BL,

         GR_SC_QTY_UN    TYPE ZCCMMESTOCKREP-GR_SC_QTY_UN,
         GR_SC_QTY_QI    TYPE ZCCMMESTOCKREP-GR_SC_QTY_QI,
         GR_SC_QTY_BL    TYPE ZCCMMESTOCKREP-GR_SC_QTY_BL,

         GR_INV_QTY_UN   TYPE ZCCMMESTOCKREP-GR_ETC_QTY_UN,
         GR_INV_QTY_QI   TYPE ZCCMMESTOCKREP-GR_ETC_QTY_QI,
         GR_INV_QTY_BL   TYPE ZCCMMESTOCKREP-GR_ETC_QTY_BL,

         GI_RETS_QTY_UN  TYPE ZCCMMESTOCKREP-GI_RETS_QTY_UN,
         GI_RETS_QTY_QI  TYPE ZCCMMESTOCKREP-GI_RETS_QTY_QI,
         GI_RETS_QTY_BL  TYPE ZCCMMESTOCKREP-GI_RETS_QTY_BL,

         SIT_QTY_UN      TYPE ZCCMMESTOCKREP-SIT_QTY_UN,
         SIT_QTY_QI      TYPE ZCCMMESTOCKREP-SIT_QTY_QI,
         SIT_QTY_BL      TYPE ZCCMMESTOCKREP-SIT_QTY_BL,

         GI_PRD_QTY_UN   TYPE ZCCMMESTOCKREP-GI_PRD_QTY_UN,
         GI_PRD_QTY_QI   TYPE ZCCMMESTOCKREP-GI_PRD_QTY_QI,
         GI_PRD_QTY_BL   TYPE ZCCMMESTOCKREP-GI_PRD_QTY_BL,

         GI_SO_QTY_UN    TYPE ZCCMMESTOCKREP-GI_SO_QTY_UN,
         GI_SO_QTY_QI    TYPE ZCCMMESTOCKREP-GI_SO_QTY_QI,
         GI_SO_QTY_BL    TYPE ZCCMMESTOCKREP-GI_SO_QTY_BL,

         GI_STO_QTY_UN   TYPE ZCCMMESTOCKREP-GI_STO_QTY_UN,
         GI_STO_QTY_QI   TYPE ZCCMMESTOCKREP-GI_STO_QTY_QI,
         GI_STO_QTY_BL   TYPE ZCCMMESTOCKREP-GI_STO_QTY_BL,
         GI_STO_QTY_ST   TYPE ZCCMMESTOCKREP-GI_STO_QTY_ST,

         GI_SL_QTY_UN    TYPE ZCCMMESTOCKREP-GI_SL_QTY_UN,
         GI_SL_QTY_QI    TYPE ZCCMMESTOCKREP-GI_SL_QTY_QI,
         GI_SL_QTY_BL    TYPE ZCCMMESTOCKREP-GI_SL_QTY_BL,

         GI_ETC_QTY_UN   TYPE ZCCMMESTOCKREP-GI_ETC_QTY_UN,
         GI_ETC_QTY_QI   TYPE ZCCMMESTOCKREP-GI_ETC_QTY_QI,
         GI_ETC_QTY_BL   TYPE ZCCMMESTOCKREP-GI_ETC_QTY_BL,

         GI_TR_QTY_UN    TYPE ZCCMMESTOCKREP-GI_TR_QTY_UN,
         GI_TR_QTY_QI    TYPE ZCCMMESTOCKREP-GI_TR_QTY_QI,
         GI_TR_QTY_BL    TYPE ZCCMMESTOCKREP-GI_TR_QTY_BL,

         GI_SC_QTY_UN    TYPE ZCCMMESTOCKREP-GI_SC_QTY_UN,
         GI_SC_QTY_QI    TYPE ZCCMMESTOCKREP-GI_SC_QTY_QI,
         GI_SC_QTY_BL    TYPE ZCCMMESTOCKREP-GI_SC_QTY_BL,

         GI_RETM_QTY_UN  TYPE ZCCMMESTOCKREP-GI_RETM_QTY_UN,
         GI_RETM_QTY_QI  TYPE ZCCMMESTOCKREP-GI_RETM_QTY_QI,
         GI_RETM_QTY_BL  TYPE ZCCMMESTOCKREP-GI_RETM_QTY_BL,

         GI_INV_QTY_UN   TYPE ZCCMMESTOCKREP-GI_INV_QTY_UN,
         GI_INV_QTY_QI   TYPE ZCCMMESTOCKREP-GI_INV_QTY_QI,
         GI_INV_QTY_BL   TYPE ZCCMMESTOCKREP-GI_INV_QTY_BL,

         MEINS           TYPE ZCCMMESTOCKREP-MEINS,

         GR_PUR_VAL_UN   TYPE ZCCMMESTOCKREP-GR_PUR_VAL_UN,
         GR_PUR_VAL_QI   TYPE ZCCMMESTOCKREP-GR_PUR_VAL_QI,
         GR_PUR_VAL_BL   TYPE ZCCMMESTOCKREP-GR_PUR_VAL_BL,

         GR_PRD_VAL_UN   TYPE ZCCMMESTOCKREP-GR_PRD_VAL_UN,
         GR_PRD_VAL_QI   TYPE ZCCMMESTOCKREP-GR_PRD_VAL_QI,
         GR_PRD_VAL_BL   TYPE ZCCMMESTOCKREP-GR_PRD_VAL_BL,

         GR_DSC_VAL_UN   TYPE ZCCMMESTOCKREP-GR_DSC_VAL_UN,
         GR_DSC_VAL_QI   TYPE ZCCMMESTOCKREP-GR_DSC_VAL_QI,
         GR_DSC_VAL_BL   TYPE ZCCMMESTOCKREP-GR_DSC_VAL_BL,

         GR_STO_VAL_UN   TYPE ZCCMMESTOCKREP-GR_STO_VAL_UN,
         GR_STO_VAL_QI   TYPE ZCCMMESTOCKREP-GR_STO_VAL_QI,
         GR_STO_VAL_BL   TYPE ZCCMMESTOCKREP-GR_STO_VAL_BL,
         GR_STO_VAL_ST   TYPE ZCCMMESTOCKREP-GR_STO_VAL_ST,

         GR_SL_VAL_UN    TYPE ZCCMMESTOCKREP-GR_SL_VAL_UN,
         GR_SL_VAL_QI    TYPE ZCCMMESTOCKREP-GR_SL_VAL_QI,
         GR_SL_VAL_BL    TYPE ZCCMMESTOCKREP-GR_SL_VAL_BL,

         GR_ETC_VAL_UN   TYPE ZCCMMESTOCKREP-GR_ETC_VAL_UN,
         GR_ETC_VAL_QI   TYPE ZCCMMESTOCKREP-GR_ETC_VAL_QI,
         GR_ETC_VAL_BL   TYPE ZCCMMESTOCKREP-GR_ETC_VAL_BL,

         GR_TR_VAL_UN    TYPE ZCCMMESTOCKREP-GR_TR_VAL_UN,
         GR_TR_VAL_QI    TYPE ZCCMMESTOCKREP-GR_TR_VAL_QI,
         GR_TR_VAL_BL    TYPE ZCCMMESTOCKREP-GR_TR_VAL_BL,

         GR_SC_VAL_UN    TYPE ZCCMMESTOCKREP-GR_SC_VAL_UN,
         GR_SC_VAL_QI    TYPE ZCCMMESTOCKREP-GR_SC_VAL_QI,
         GR_SC_VAL_BL    TYPE ZCCMMESTOCKREP-GR_SC_VAL_BL,

         GR_INV_VAL_UN   TYPE ZCCMMESTOCKREP-GR_INV_VAL_UN,
         GR_INV_VAL_QI   TYPE ZCCMMESTOCKREP-GR_INV_VAL_QI,
         GR_INV_VAL_BL   TYPE ZCCMMESTOCKREP-GR_INV_VAL_BL,

         GI_RETS_VAL_UN  TYPE ZCCMMESTOCKREP-GI_RETS_VAL_UN,
         GI_RETS_VAL_QI  TYPE ZCCMMESTOCKREP-GI_RETS_VAL_QI,
         GI_RETS_VAL_BL  TYPE ZCCMMESTOCKREP-GI_RETS_VAL_BL,

         SIT_VAL_UN      TYPE ZCCMMESTOCKREP-SIT_VAL_UN,
         SIT_VAL_QI      TYPE ZCCMMESTOCKREP-SIT_VAL_QI,
         SIT_VAL_BL      TYPE ZCCMMESTOCKREP-SIT_VAL_BL,

         GI_PRD_VAL_UN   TYPE ZCCMMESTOCKREP-GI_PRD_VAL_UN,
         GI_PRD_VAL_QI   TYPE ZCCMMESTOCKREP-GI_PRD_VAL_QI,
         GI_PRD_VAL_BL   TYPE ZCCMMESTOCKREP-GI_PRD_VAL_BL,

         GI_SO_VAL_UN    TYPE ZCCMMESTOCKREP-GI_SO_VAL_UN,
         GI_SO_VAL_QI    TYPE ZCCMMESTOCKREP-GI_SO_VAL_QI,
         GI_SO_VAL_BL    TYPE ZCCMMESTOCKREP-GI_SO_VAL_BL,

         GI_STO_VAL_UN   TYPE ZCCMMESTOCKREP-GI_STO_VAL_UN,
         GI_STO_VAL_QI   TYPE ZCCMMESTOCKREP-GI_STO_VAL_QI,
         GI_STO_VAL_BL   TYPE ZCCMMESTOCKREP-GI_STO_VAL_BL,
         GI_STO_VAL_ST   TYPE ZCCMMESTOCKREP-GI_STO_VAL_ST,

         GI_SL_VAL_UN    TYPE ZCCMMESTOCKREP-GI_SL_VAL_UN,
         GI_SL_VAL_QI    TYPE ZCCMMESTOCKREP-GI_SL_VAL_QI,
         GI_SL_VAL_BL    TYPE ZCCMMESTOCKREP-GI_SL_VAL_BL,

         GI_ETC_VAL_UN   TYPE ZCCMMESTOCKREP-GI_ETC_VAL_UN,
         GI_ETC_VAL_QI   TYPE ZCCMMESTOCKREP-GI_ETC_VAL_QI,
         GI_ETC_VAL_BL   TYPE ZCCMMESTOCKREP-GI_ETC_VAL_BL,

         GI_TR_VAL_UN    TYPE ZCCMMESTOCKREP-GI_TR_VAL_UN,
         GI_TR_VAL_QI    TYPE ZCCMMESTOCKREP-GI_TR_VAL_QI,
         GI_TR_VAL_BL    TYPE ZCCMMESTOCKREP-GI_TR_VAL_BL,

         GI_SC_VAL_UN    TYPE ZCCMMESTOCKREP-GI_SC_VAL_UN,
         GI_SC_VAL_QI    TYPE ZCCMMESTOCKREP-GI_SC_VAL_QI,
         GI_SC_VAL_BL    TYPE ZCCMMESTOCKREP-GI_SC_VAL_BL,

         GI_RETM_VAL_UN  TYPE ZCCMMESTOCKREP-GI_RETM_VAL_UN,
         GI_RETM_VAL_QI  TYPE ZCCMMESTOCKREP-GI_RETM_VAL_QI,
         GI_RETM_VAL_BL  TYPE ZCCMMESTOCKREP-GI_RETM_VAL_BL,

         GI_INV_VAL_UN   TYPE ZCCMMESTOCKREP-GI_INV_VAL_UN,
         GI_INV_VAL_QI   TYPE ZCCMMESTOCKREP-GI_INV_VAL_QI,
         GI_INV_VAL_BL   TYPE ZCCMMESTOCKREP-GI_INV_VAL_BL,

         WAERS           TYPE ZCCMMESTOCKREP-WAERS,
         LASTQTY_SIT     TYPE ZCCMMESTOCKREP-LASTQTY_SIT,
         LASTQTY_UN      TYPE ZCCMMESTOCKREP-LASTQTY_UN,
         LASTQTY_QI      TYPE ZCCMMESTOCKREP-LASTQTY_QI,
         LASTQTY_BL      TYPE ZCCMMESTOCKREP-LASTQTY_BL,
         LASTQTY_GRUN    TYPE ZCCMMESTOCKREP-LASTQTY_GRUN,
         LASTQTY_GRQI    TYPE ZCCMMESTOCKREP-LASTQTY_GRQI,
         LASTQTY_GRBL    TYPE ZCCMMESTOCKREP-LASTQTY_GRBL,
         LASTQTY_GIUN    TYPE ZCCMMESTOCKREP-LASTQTY_GIUN,
         LASTQTY_GIQI    TYPE ZCCMMESTOCKREP-LASTQTY_GIQI,
         LASTQTY_GIBL    TYPE ZCCMMESTOCKREP-LASTQTY_GIBL,
       END OF TY_DATA.

"*- Alv Dispaly
TYPES: BEGIN OF TS_DISP.
         INCLUDE TYPE ZSCN00003.  "필수!! ALV Changed Common Struc.. (STATU/CELLS/CELLC/MSGTB/DCFLG)
         INCLUDE TYPE TY_DATA.    "Table 에 ZDELE가 없을 경우 필드 추가 필수
"Dcflg=> C:Create U:Update T:라인삭제 '' :Original
TYPES: CDLST(30),
         ZDELE,                  "필수필드임 (테이블에 있을경우는 생략)
         NEW,                    "신규데이타
       END OF  TS_DISP.

TYPES: BEGIN OF TY_DETAIL,
         MJAHR      TYPE ZCCMMDOCDETAIL-MJAHR,
         MBLNR      TYPE ZCCMMDOCDETAIL-MBLNR,
         ZEILE      TYPE ZCCMMDOCDETAIL-ZEILE,
         BUKRS      TYPE ZCCMMDOCDETAIL-BUKRS,
         WERKS      TYPE ZCCMMDOCDETAIL-WERKS,
         NAME1      TYPE ZCCMMDOCDETAIL-NAME1,
         LGORT      TYPE ZCCMMDOCDETAIL-LGORT,
         LGOBE      TYPE ZCCMMDOCDETAIL-LGOBE,
         MATNR      TYPE ZCCMMDOCDETAIL-MATNR,
         MAKTX      TYPE ZCCMMDOCDETAIL-MAKTX,
         CHARG      TYPE ZCCMMDOCDETAIL-CHARG,
         BUDAT      TYPE ZCCMMDOCDETAIL-BUDAT,
         UMWRK      TYPE ZCCMMDOCDETAIL-UMWRK,
         TOPLANT    TYPE ZCCMMDOCDETAIL-TOPLANT,
         UMLGO      TYPE ZCCMMDOCDETAIL-UMLGO,
         TOSTORAGE  TYPE ZCCMMDOCDETAIL-TOSTORAGE,
         SOBKZ      TYPE ZCCMMDOCDETAIL-SOBKZ,
         LIFNR      TYPE ZCCMMDOCDETAIL-LIFNR,
         VENDORNAME TYPE ZCCMMDOCDETAIL-VENDORNAME,
         LBBSA_SID  TYPE ZCCMMDOCDETAIL-LBBSA_SID,
         BSTAUS_SG  TYPE ZCCMMDOCDETAIL-BSTAUS_SG,
         BSTAUS_CG  TYPE ZCCMMDOCDETAIL-BSTAUS_CG,
         BWART      TYPE ZCCMMDOCDETAIL-BWART,
         BTEXT      TYPE ZCCMMDOCDETAIL-BTEXT,
         BWTAR      TYPE ZCCMMDOCDETAIL-BWTAR,
         KZBEW      TYPE ZCCMMDOCDETAIL-KZBEW,
         MOVEGROUP  TYPE ZCCMMDOCDETAIL-MOVEGROUP,
         STOCK_QTY  TYPE ZCCMMDOCDETAIL-STOCK_QTY,
         MEINS      TYPE ZCCMMDOCDETAIL-MEINS,
         SHKZG      TYPE ZCCMMDOCDETAIL-SHKZG,
         BKTXT      TYPE ZCCMMDOCDETAIL-BKTXT,
         ZTYPE      TYPE ZCCMMDOCDETAIL-ZTYPE,
       END OF TY_DETAIL.

"*- Alv Dispaly
TYPES: BEGIN OF TS_DISP_0200.
         INCLUDE TYPE ZSCN00003.  "필수!! ALV Changed Common Struc.. (STATU/CELLS/CELLC/MSGTB/DCFLG)
         INCLUDE TYPE TY_DETAIL.    "Table 에 ZDELE가 없을 경우 필드 추가 필수
"Dcflg=> C:Create U:Update T:라인삭제 '' :Original
TYPES: CDLST(30),
         ZDELE,                  "필수필드임 (테이블에 있을경우는 생략)
         NEW,                    "신규데이타
       END OF  TS_DISP_0200.

TYPES: BEGIN OF TY_PDF_BASE1,
         BUKRS     TYPE ZCCMMESTOCKREP-BUKRS,
         WERKS     TYPE ZCCMMESTOCKREP-WERKS,
         MATNR     TYPE ZCCMMESTOCKREP-MATNR,
         MAKTX     TYPE ZCCMMESTOCKREP-MAKTX,
         INITSTOCK TYPE ZCCMMESTOCKREP-INITSTOCK,
         MEINS     TYPE ZCCMMESTOCKREP-MEINS,
       END OF TY_PDF_BASE1,
       TY_T_PDF_BASE1 TYPE TABLE OF TY_PDF_BASE1.

TYPES: BEGIN OF TY_PDF_BASE2,
         MATNR  TYPE MATDOC-MATNR,
         BUDAT  TYPE MATDOC-BUDAT,
         GUBUN  TYPE CHAR1,            "A:입고 , B:출고 (정렬용도)
         INQTY  TYPE MATDOC-STOCK_QTY,
         OUTQTY TYPE MATDOC-STOCK_QTY,
         MEINS  TYPE MATDOC-MEINS,
         NAME1  TYPE LFA1-NAME1,
         STCD2  TYPE LFA1-STCD2,
         ADDR   TYPE CHAR70,
         TELF1  TYPE LFA1-TELF1,
       END OF TY_PDF_BASE2,
       TY_T_PDF_BASE2 TYPE TABLE OF TY_PDF_BASE2.

DATA : GS_CONTROL TYPE SSFCTRLOP,
       GS_OUTPUT  TYPE SSFCOMPOP. " 스마트 편집기 옵션

*----------------------------------------------------------------------*
* ALV Object
*----------------------------------------------------------------------*
DATA : GRF_DOCKING_CON TYPE REF TO CL_GUI_DOCKING_CONTAINER,
       GRF_DOCKING_CON_0200 TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GRF_HEAD TYPE REF TO CL_GUI_CONTAINER,
       GRF_BODY TYPE REF TO CL_GUI_CONTAINER.

DATA : GRF_GRID TYPE REF TO LCL_CUST_ALV_GRID. " ALV Gridv

DATA : GRF_HEAD_0200 TYPE REF TO CL_GUI_CONTAINER.

DATA : GRF_GRID_0200 TYPE REF TO LCL_CUST_ALV_GRID. " ALV Gridv
*----------------------------------------------------------------------*
* Global Data
*----------------------------------------------------------------------*
DATA: GT_DATA TYPE TABLE OF TY_DATA.
DATA: GT_DISP TYPE TABLE OF TS_DISP,
      GT_DISP_0200 TYPE TABLE OF TS_DISP_0200.

DATA: OK_CODE TYPE SY-UCOMM,
      GV_MODE           TYPE C VALUE '',                          "Display :D  Edit:E (화면편집)
      GV_OK_CODE        TYPE SY-UCOMM,
      OK_CODE_DETAIL    TYPE SY-UCOMM,
      GV_OK_CODE_DETAIL TYPE SY-UCOMM,
      GV_MODE_DETAIL.

DATA: GV_TCNT TYPE SY-TABIX.

DATA : GS_VARIANT TYPE DISVARIANT. " Variant
DATA : GV_NAME1 TYPE T001W-NAME1,
       GV_LGOBE TYPE T001L-LGOBE.

*----------------------------------------------------------------------*
* Macros
*----------------------------------------------------------------------*
************************************************************************
DEFINE _G_APPEND_VALUE.
  &1-OPTION = &2.
  &1-SIGN   = &3.
  &1-LOW    = &4.
  &1-HIGH   = &5.
  APPEND &1.
END-OF-DEFINITION.

DEFINE _G_INIT.

  CLEAR:&1, &1[].

END-OF-DEFINITION .

DEFINE _G_SET_VALUE.

  &1 = &2.

END-OF-DEFINITION .
