*&---------------------------------------------------------------------*
*& Include          ZRMM3010SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-B01.

  "회사코드
  PARAMETERS: P_BUKRS TYPE T001-BUKRS.
*  PARAMETERS: P_BUKRS TYPE T001-BUKRS AS LISTBOX
*                                      VISIBLE LENGTH 23
*                                      OBLIGATORY
*                                      MODIF ID EXC USER-COMMAND D.

SELECTION-SCREEN END OF BLOCK BLK1.

SELECTION-SCREEN BEGIN OF BLOCK BLK2 WITH FRAME TITLE TEXT-B02.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-F02.
    "개요
    PARAMETERS: P_RA RADIOBUTTON GROUP G1 DEFAULT 'X'.
    SELECTION-SCREEN COMMENT (10) TEXT-F03 FOR FIELD P_RA.

    "상세
    PARAMETERS: P_RB RADIOBUTTON GROUP G1.
    SELECTION-SCREEN COMMENT (10) TEXT-F04 FOR FIELD P_RB.
  SELECTION-SCREEN END OF LINE.

  "PR 상태
*U3> 외부적인 표시는 언어별로/내부적으로는 한글로 - START
*  PARAMETERS: P_WFSTS TYPE ZSVCMMPR_RELEASE-WF_STAUS AS LISTBOX
  PARAMETERS: P_WFSTS TYPE CHAR50 AS LISTBOX
*U3> 외부적인 표시는 언어별로/내부적으로는 한글로 - END
                                                     VISIBLE LENGTH 18
                                                     OBLIGATORY.

  SELECT-OPTIONS: S_BSART  FOR ZSVCMMPR_RELEASE-BSART,             "요청유형
                  S_BADAT  FOR ZSVCMMPR_RELEASE-BADAT,             "요청일
                  S_BANFN  FOR ZSVCMMPR_RELEASE-BANFN,             "구매요청
                  S_MATNR  FOR ZSVCMMPR_RELEASE-MATNR,             "자재
*                  S_RQDEPT FOR ZSVCMMPR_RELEASE-ZPEQ_DEPARTMENT,   "요청부서
*                  S_RQUSER FOR ZSVCMMPR_RELEASE-ZREQUESTER,        "요청자
                  S_PSTYP  FOR ZSVCMMPR_RELEASE-PSTYP,             "품목범주
                  S_KNTTP  FOR ZSVCMMPR_RELEASE-KNTTP,             "계정지정
                  S_EKGRP  FOR ZSVCMMPR_RELEASE-EKGRP,             "구매그룹
                  S_WERKS  FOR ZSVCMMPR_RELEASE-WERKS,             "플랜트
                  S_DISPO  FOR ZSVCMMPR_RELEASE-DISPO,             "MRP관리자
                  S_MATKL  FOR ZSVCMMPR_RELEASE-MATKL,             "자재그룹
                  S_ESTKZ  FOR ZSVCMMPR_RELEASE-ESTKZ.             "생성지시자

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-F05 MODIF ID DOM.
    "긴급여부
*    PARAMETERS: P_URGEN TYPE ZSVCMMPR_RELEASE-ZURGENT AS CHECKBOX MODIF ID DOM.
*    SELECTION-SCREEN COMMENT (10) TEXT-F06 FOR FIELD P_URGEN MODIF ID DOM.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-F05 MODIF ID DOM.
    "선투입여부
*    PARAMETERS: P_PREIN TYPE ZSVCMMPR_RELEASE-ZPRE_INPUT AS CHECKBOX MODIF ID DOM.
*    SELECTION-SCREEN COMMENT (18) TEXT-F07 FOR FIELD P_PREIN MODIF ID DOM.
  SELECTION-SCREEN END OF LINE.

*  PARAMETERS: P_URGEN TYPE ZSVCMMPR_RELEASE-ZURGENT AS CHECKBOX,
*              P_PREIN TYPE ZSVCMMPR_RELEASE-ZPRE_INPUT AS CHECKBOX.

  SELECT-OPTIONS: S_EBAKZ FOR ZSVCMMPR_RELEASE-EBAKZ NO INTERVALS NO-EXTENSION,   "마감
                  S_FIXKZ FOR ZSVCMMPR_RELEASE-FIXKZ NO INTERVALS NO-EXTENSION,   "고정지시자
                  S_LOEKZ FOR ZSVCMMPR_RELEASE-LOEKZ NO INTERVALS NO-EXTENSION.   "삭제지시자

*  PARAMETERS: P_ZRECEI TYPE ZSVCMMPR_RELEASE-ZRECEIPT AS LISTBOX VISIBLE LENGTH 15 MODIF ID DOM.

SELECTION-SCREEN END OF BLOCK BLK2.

*---------------------------------------------------------------------*
* AT SELECTION-SCREEN ON VALUE-REQUEST FOR
*---------------------------------------------------------------------*

* 플랜트 F4
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_WERKS-LOW.
  PERFORM SET_F4_WERKS USING 'S_WERKS-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_WERKS-HIGH.
  PERFORM SET_F4_WERKS USING 'S_WERKS-HIGH'.

* 구매요청유형 F4
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_BSART-LOW.
  PERFORM SET_F4_BSART USING 'S_BSART-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_BSART-HIGH.
  PERFORM SET_F4_BSART USING 'S_BSART-HIGH'.

* 구매그룹 F4
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_EKGRP-LOW.
  PERFORM SET_F4_EKGRP USING 'S_EKGRP-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_EKGRP-HIGH.
  PERFORM SET_F4_EKGRP USING 'S_EKGRP-HIGH'.

** 요청부서 F4
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_RQDEPT-LOW.
*  PERFORM SET_F4_DEPAT USING 'S_RQDEPT-LOW'.
*
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_RQDEPT-HIGH.
*  PERFORM SET_F4_DEPAT USING 'S_RQDEPT-HIGH'.
*
** 요청자 F4
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_RQUSER-LOW.
*  PERFORM SET_F4_PERSN USING 'S_RQUSER-LOW'.
*
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_RQUSER-HIGH.
*  PERFORM SET_F4_PERSN USING 'S_RQUSER-HIGH'.
*
**---------------------------------------------------------------------*
** AT SELECTION-SCREEN OUTPUT
**---------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.

  PERFORM SET_LIST_BOX.

**----------------------------------------------------------------------*
** Screen Parameter Control
**----------------------------------------------------------------------*
*
  PERFORM SET_SEL_SCREEN.
