*&---------------------------------------------------------------------*
*& Include          ZRMM4420SCR
*&---------------------------------------------------------------------*
"-----------------------------------------------------------------------
" 기본선택
"-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-B01.
  PARAMETERS:     P_BUKRS LIKE T001-BUKRS OBLIGATORY.       "회사코드
  SELECTION-SCREEN COMMENT 40(25) GV_BUTXT FOR FIELD P_BUKRS.
  SELECT-OPTIONS: S_BUDAT FOR MKPF-BUDAT  OBLIGATORY,       "조회기간
                  S_WERKS FOR T001W-WERKS OBLIGATORY,       "플랜트
                  S_LGORT FOR T001L-LGORT MODIF ID SC1,     "저장위치
                  S_EKGRP FOR MARC-EKGRP,                   "구매그룹
                  S_DISPO FOR MARC-DISPO,                   "MRP 관리자
                  S_LIFNR FOR LFA1-LIFNR MODIF ID SC2,      "업체코드
                  S_MATKL FOR MARA-MATKL,                   "자재그룹
                  S_MATNR FOR MARA-MATNR,                   "자재
                  S_CHARG FOR MCH1-CHARG.                   "배치
*                  S_BKLAS FOR MBEW-BKLAS.                   "평가클래스 *U6 개발 "U09 KTGA-3924: 평가클래스 삭제 BKLAS 20230109

SELECTION-SCREEN END OF BLOCK BLK1.

"-----------------------------------------------------------------------
" 기간유형
"-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLK2 WITH FRAME TITLE TEXT-B02.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 4.
    PARAMETERS: P_RD1A RADIOBUTTON GROUP RD1 DEFAULT 'X' USER-COMMAND RA1.
    SELECTION-SCREEN COMMENT 6(8) TEXT-T01 FOR FIELD P_RD1A.  "Daily
    SELECTION-SCREEN POSITION 20.
    PARAMETERS: P_RD1B RADIOBUTTON GROUP RD1.
    SELECTION-SCREEN COMMENT 24(8) TEXT-T02 FOR FIELD P_RD1B.  "Monthly
    SELECTION-SCREEN POSITION 38.
    PARAMETERS: P_RD1C RADIOBUTTON GROUP RD1.
    SELECTION-SCREEN COMMENT 40(8) TEXT-T03 FOR FIELD P_RD1C.  "Quarter
    SELECTION-SCREEN POSITION 60.
    PARAMETERS: P_RD1D RADIOBUTTON GROUP RD1.
    SELECTION-SCREEN COMMENT 62(8) TEXT-T04 FOR FIELD P_RD1D.  "Yearly
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK BLK2.

"-----------------------------------------------------------------------
" 작업구분
"-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLK3 WITH FRAME TITLE TEXT-B03.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 4.
    PARAMETERS: P_RD2A RADIOBUTTON GROUP RD2 DEFAULT 'X' USER-COMMAND RA2.
    SELECTION-SCREEN COMMENT 6(12) TEXT-T05 FOR FIELD P_RD2A.  "Total 재고
    SELECTION-SCREEN POSITION 20.
    PARAMETERS: P_RD2B RADIOBUTTON GROUP RD2.
    SELECTION-SCREEN COMMENT 24(13) TEXT-T06 FOR FIELD P_RD2B.  "저장위치 재고
    SELECTION-SCREEN POSITION 38.
    PARAMETERS: P_RD2C RADIOBUTTON GROUP RD2.
    SELECTION-SCREEN COMMENT 39(15) TEXT-T07 FOR FIELD P_RD2C.  "업체 SC 재고
    SELECTION-SCREEN POSITION 60.
    PARAMETERS: P_RD2D RADIOBUTTON GROUP RD2.
    SELECTION-SCREEN COMMENT 61(15) TEXT-T08 FOR FIELD P_RD2D.  "업체 위탁 재고
    SELECTION-SCREEN POSITION 78.
    PARAMETERS: P_RD2E RADIOBUTTON GROUP RD2.
    SELECTION-SCREEN COMMENT 79(20) TEXT-T14 FOR FIELD P_RD2E.  "고객 판매 재고
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK BLK3.

"-----------------------------------------------------------------------
" 재고유형
"-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLK4 WITH FRAME TITLE TEXT-B04.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 4.
    PARAMETERS: P_RD3A RADIOBUTTON GROUP RD3 DEFAULT 'X' USER-COMMAND RA3.
    SELECTION-SCREEN COMMENT 6(8) TEXT-T09 FOR FIELD P_RD3A.  "전체
    SELECTION-SCREEN POSITION 20.
    PARAMETERS: P_RD3B RADIOBUTTON GROUP RD3.
    SELECTION-SCREEN COMMENT 24(13) TEXT-T10 FOR FIELD P_RD3B.  "가용 재고
    SELECTION-SCREEN POSITION 38.
    PARAMETERS: P_RD3C RADIOBUTTON GROUP RD3.
    SELECTION-SCREEN COMMENT 40(16) TEXT-T11 FOR FIELD P_RD3C.  "품질 검사 중 재고
    SELECTION-SCREEN POSITION 60.
    PARAMETERS: P_RD3D RADIOBUTTON GROUP RD3.
    SELECTION-SCREEN COMMENT 62(12) TEXT-T12 FOR FIELD P_RD3D.  "보류 재고
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK BLK4.

"-----------------------------------------------------------------------
" BATCH 조회
"-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLK5 WITH FRAME TITLE TEXT-B05.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 4.
    PARAMETERS: P_CHK1 AS CHECKBOX DEFAULT ''.
    SELECTION-SCREEN COMMENT 6(30) TEXT-T13. "BATCH 단위 확장
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK BLK5.

"-----------------------------------------------------------------------
" 출력 Layout
"-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLKV WITH FRAME TITLE TEXT-B06.
  PARAMETERS: P_VAR LIKE DISVARIANT-VARIANT.
SELECTION-SCREEN END OF BLOCK BLKV.

*----------------------------------------------------------------------*
* AT SELECTION-SCREEN
*----------------------------------------------------------------------*
AT SELECTION-SCREEN.

  IF SY-UCOMM = GC_RA2.
    _G_INIT : S_WERKS, S_LGORT, S_LIFNR, S_MATNR, S_CHARG, S_MATKL.
    CLEAR : P_VAR.
  ENDIF.

*---------------------------------------------------------------------*
* AT SELECTION-SCREEN ON
*---------------------------------------------------------------------*
* CHECK_AUTHORITY

AT SELECTION-SCREEN ON P_BUKRS.
  PERFORM BUKRS_CHECK USING P_BUKRS.

AT SELECTION-SCREEN ON S_WERKS.
  PERFORM WERKS_CHECK USING S_WERKS-LOW.
  PERFORM WERKS_CHECK USING S_WERKS-HIGH.

AT SELECTION-SCREEN ON S_LGORT.
  PERFORM LGORT_CHECK USING S_LGORT-LOW.
  PERFORM LGORT_CHECK USING S_LGORT-HIGH.

*---------------------------------------------------------------------*
* AT SELECTION-SCREEN ON VALUE-REQUEST FOR
*---------------------------------------------------------------------*

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_WERKS-LOW.
  PERFORM VARIANT_F4_1000 USING 'WERKS' 'GV_NAME1' 'LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_WERKS-HIGH.
  PERFORM VARIANT_F4_1000 USING 'WERKS' 'GV_NAME1' 'HIGH'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_LGORT-LOW.
  PERFORM VARIANT_F4_1000 USING 'LGORT' 'GV_LGOBE' 'LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_LGORT-HIGH.
  PERFORM VARIANT_F4_1000 USING 'LGORT' 'GV_LGOBE' 'HIGH'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_DISPO-LOW.
  PERFORM VARIANT_F4_1000 USING 'DISPO' 'GV_DISPO' 'LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_DISPO-HIGH.
  PERFORM VARIANT_F4_1000 USING 'DISPO' 'GV_DISPO' 'HIGH'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_VAR.
  PERFORM VARIANT_F4 USING GS_VARIANT CHANGING P_VAR.

*----------------------------------------------------------------------*
* AT SELECTION-SCREEN OUTPUT
*----------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.

  PERFORM SELECTION_SCREEN_OUTPUT.
