*&---------------------------------------------------------------------*
*& Include          ZRMM3030SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-B01.

  "회사코드
  PARAMETERS: P_BUKRS TYPE EKKO-BUKRS.
*  PARAMETERS: P_BUKRS TYPE EKKO-BUKRS AS LISTBOX
*                                      VISIBLE LENGTH 23
*                                      OBLIGATORY
*                                      MODIF ID EXC.

  SELECT-OPTIONS: S_WERKS FOR EKPO-WERKS,
                  S_BUDAT FOR MKPF-BUDAT OBLIGATORY,
                  S_LIFNR FOR EKKO-LIFNR,
                  S_MATNR FOR EKPO-MATNR,
                  S_MATKL FOR EKPO-MATKL,         "자재그룹
                  S_TAXIM FOR MLAN-TAXIM,         "세금지시자
                  S_EKGRP FOR EKKO-EKGRP,
                  S_BSART FOR EKKO-BSART,
                  S_EBELN FOR EKKO-EBELN,
                  S_ORDER FOR EKKO-ZORDER_PERSON,
                  S_DEPTO FOR EKKO-ZORDER_DEPARTMENT.

SELECTION-SCREEN END OF BLOCK BLK1.

* 선택조건
SELECTION-SCREEN BEGIN OF BLOCK BLK2 WITH FRAME TITLE TEXT-B02.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_RS1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND RC1.  "물품일반
    SELECTION-SCREEN COMMENT (15) TEXT-F02 FOR FIELD P_RS1.

    PARAMETERS P_RS2 RADIOBUTTON GROUP R1.  "물품선급
    SELECTION-SCREEN COMMENT (15) TEXT-F03 FOR FIELD P_RS2.

    PARAMETERS P_RS3 RADIOBUTTON GROUP R1 MODIF ID RS3.  "자율납품&위탁정산
    SELECTION-SCREEN COMMENT (20) TEXT-F04 FOR FIELD P_RS3.

    PARAMETERS P_RS4 RADIOBUTTON GROUP R1.  "공사용역
    SELECTION-SCREEN COMMENT (20) TEXT-F05 FOR FIELD P_RS4.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLK2.

* 세금계산서 작성방법
SELECTION-SCREEN BEGIN OF BLOCK BLK3 WITH FRAME TITLE TEXT-B03.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_RB1 RADIOBUTTON GROUP R2 MODIF ID MRB. "정발행
    SELECTION-SCREEN COMMENT (15) TEXT-F06 FOR FIELD P_RB1.

    PARAMETERS P_RB2 RADIOBUTTON GROUP R2 MODIF ID MRB. "역발행
    SELECTION-SCREEN COMMENT (15) TEXT-F07 FOR FIELD P_RB2.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLK3.

*---------------------------------------------------------------------*
* AT SELECTION-SCREEN ON VALUE-REQUEST FOR
*---------------------------------------------------------------------*

* 플랜트 F4
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_WERKS-LOW.
  PERFORM SET_F4_WERKS USING 'S_WERKS-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_WERKS-HIGH.
  PERFORM SET_F4_WERKS USING 'S_WERKS-HIGH'.

* 문서유형 F4
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_BSART-LOW.
  PERFORM SET_F4_BSART USING 'S_BSART-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_BSART-HIGH.
  PERFORM SET_F4_BSART USING 'S_BSART-HIGH'.

* 구매그룹 F4
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_EKGRP-LOW.
  PERFORM SET_F4_EKGRP USING 'S_EKGRP-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_EKGRP-HIGH.
  PERFORM SET_F4_EKGRP USING 'S_EKGRP-HIGH'.

** 발주담당자 F4
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_ORDER-LOW.
*  PERFORM SET_F4_ORDER USING 'S_ORDER-LOW'.
*
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_ORDER-HIGH.
*  PERFORM SET_F4_ORDER USING 'S_ORDER-HIGH'.
*
** 발주부서 F4
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_DEPTO-LOW.
*  PERFORM SET_F4_DEPTO USING 'S_DEPTO-LOW'.
*
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_DEPTO-HIGH.
*  PERFORM SET_F4_DEPTO USING 'S_DEPTO-HIGH'.
*
**U2> 세금지시자 (LOCAL LAND 에 의해 설정) - START
AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_TAXIM-LOW.
  PERFORM SET_F4_TAXIM USING 'S_TAXIM-LOW'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_TAXIM-HIGH.
  PERFORM SET_F4_TAXIM USING 'S_TAXIM-HIGH'.
**U2> 세금지시자 (LOCAL LAND 에 의해 설정) - END
*---------------------------------------------------------------------*
* AT SELECTION-SCREEN OUTPUT
*---------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.

  PERFORM SET_LIST_BOX.

*----------------------------------------------------------------------*
* Screen Parameter Control
*----------------------------------------------------------------------*

  PERFORM SET_SEL_SCREEN.
